# Generated by Django 5.0.6 on 2024-06-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mobile Recharge', 'Mobile Recharge'), ('DTH Recharge', 'DTH Recharge'), ('Insurance payment', 'Insurance payment')], max_length=40)),
                ('payment_type', models.CharField(choices=[('UPI', 'UPI'), ('internet banking', 'internet banking'), ('card payment', 'card payment')], max_length=40)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.serviceuser')),
            ],
        ),
    ]
